version: 2

project_name: termfolio

before:
  hooks:
    - go mod tidy

git:
  ignore_tags:
    - "{{ if not .IsNightly }}*-rc*{{ end }}"

builds:
  - id: termfolio
    binary: termfolio
    env:
      - CGO_ENABLED=0
    tags:
      - netgo
      - osusergo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: termfolio
    name_template: >-
      termfolio-
      {{- if eq .Os "darwin" }}darwin{{- else if eq .Os "linux" }}linux{{- else if eq .Os "windows" }}windows{{- else if eq .Os "freebsd" }}freebsd{{- else if eq .Os "openbsd" }}openbsd{{- else if eq .Os "netbsd" }}netbsd{{- else if eq .Os "dragonfly" }}dragonfly{{- else }}{{ .Os }}{{ end }}-
      {{- if eq .Arch "amd64" }}x86-64{{- else if eq .Arch "386" }}i386{{- else if eq .Arch "arm64" }}aarch64{{- else if eq .Arch "arm" }}armv{{ .Arm }}{{- else if eq .Arch "mips" }}mips{{- if .Mips }}-{{ .Mips }}{{ end }}{{- else if eq .Arch "mipsle" }}mipsle{{- if .Mips }}-{{ .Mips }}{{ end }}{{- else if eq .Arch "mips64" }}mips64{{- if .Mips }}-{{ .Mips }}{{ end }}{{- else if eq .Arch "mips64le" }}mips64le{{- if .Mips }}-{{ .Mips }}{{ end }}{{- else if eq .Arch "ppc64" }}ppc64{{- else if eq .Arch "ppc64le" }}ppc64le{{- else if eq .Arch "riscv64" }}riscv64{{- else if eq .Arch "s390x" }}s390x{{- else }}{{ .Arch }}{{ end }}-
      {{- .Tag }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: git
  format: "- [`{{ .SHA }}`](https://github.com/andatoshiki/termfolio/commit/{{ .SHA }}): {{ .Message }}"
  abbrev: 7

release:
  prerelease: auto
  header: |
    # {{ .Tag }} Changes

homebrew_casks:
  - name: termfolio
    binary: termfolio
    homepage: "https://github.com/andatoshiki/termfolio"
    description: "SSH-based interactive portfolio application"
    url:
      template: "https://github.com/andatoshiki/termfolio/releases/download/{{ .Tag }}/termfolio-darwin-{{ if eq .Arch \"arm64\" }}aarch64{{ else }}x86-64{{ end }}-{{ .Tag }}.tar.gz"
      verified: "github.com/andatoshiki/termfolio"
    commit_msg_template: "brew cask update for termfolio version {{ .Tag }}"
    directory: Casks
    caveats: |
      If you see a damaged app warning, run:
        xattr -dr com.apple.quarantine $(brew --prefix)/Caskroom/termfolio/*/termfolio
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termfolio"]
          end
    repository:
      owner: andatoshiki
      name: homebrew-tap
      branch: main
      pull_request:
        enabled: true
        draft: false
